/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fruit_cream_cake.glb 
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fruit-cream-cake-d1b442b228e6422f8877bab8f8a6bfec
Title: Fruit Cream Cake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fruit_cream_cake.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['03___Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.CL_LR_Baked1} />
      </group>
    </group>
  )
}

useGLTF.preload('/fruit_cream_cake.glb')
